name: globegaze
description: "A travel app for strangers"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cool_alert: ^2.0.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  icons_plus: ^5.0.0
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.1
  loading_animation_widget: ^1.2.1
  email_otp: ^3.0.2
  convex_bottom_bar: ^3.2.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  search_app_bar_page: ^2.3.1
  url_launcher: ^6.1.7
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  emoji_picker_flutter: ^4.3.0
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.6.0
  flutter_notification_channel: ^3.1.0
  encrypt: ^5.0.3
  google_generative_ai: ^0.4.6
  audioplayers: ^6.1.2
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  wechat_assets_picker: ^9.3.3
  video_compress: ^3.1.3
  image: ^4.3.0
  ffmpeg_kit_flutter: ^6.0.3
  provider: ^6.1.2
  location: ^8.0.0
  firebase_app_check: ^0.3.1+4
  get: ^4.6.6
  flare_flutter: ^3.0.2
  photo_manager: ^3.6.4 # Downgraded dependency
  rxdart:
  flutter_riverpod:
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animation/
    - assets/svg_images/
    - assets/png_jpeg_images/
    - assets/privetApi/
    - assets/sounds/
    - assets/png_jpeg_images/user.png
fonts:
  - family: MonaSans
    fonts:
      - assets/fonts/MonaSans-Bold.ttf
    flutter_icons:
      android: true
      ios: true
      image_path: "assets/png_jpeg_images/AppIcon.png"
